function STAR = STAR_ID(Data,Pair,ac_er_ang, ac_er_dis,i,j,k)
    
    %Calculate 3 sets of distance and angle by 3 peaks of triangle
    [dis1,dis2,agl1] = StarPair(Data,i,j,k);
    [dis3,dis4,agl2] = StarPair(Data,j,i,k);
    [dis5,dis6,agl3] = StarPair(Data,k,i,j);
    %% Set 1
    Pair1 = Pair;
    
    % Elimination by angle 
    aglmin      = agl1 - ac_er_ang;
    aglmax      = agl1 + ac_er_ang;
    Pair1(:,7)  = (Pair1(:,6)>aglmin)&(Pair1(:,6)<aglmax);
    Pair1       =  Pair1(Pair1(:,7)>0,:);
    % Elimination by distance ratio
    dis_s1    = dis1/dis2;
    dis_s2    = dis2/dis1;
    dis_s     =    [dis_s1-ac_er_dis;...
                    dis_s1+ac_er_dis;...
                    dis_s2-ac_er_dis;...
                    dis_s2+ac_er_dis];
    Pair1(:,7) =    ((dis_s(1)<(Pair1(:,4)./Pair1(:,5)))&...
                    (dis_s(2)>(Pair1(:,4)./Pair1(:,5))))|...
                    ((dis_s(3)<(Pair1(:,4)./Pair1(:,5)))&...
                    (dis_s(4)>(Pair1(:,4)./Pair1(:,5))))|...
                    ((dis_s(1)<(Pair1(:,5)./Pair1(:,4)))&...
                    (dis_s(2)>(Pair1(:,5)./Pair1(:,4))))|...
                    ((dis_s(3)<(Pair1(:,5)./Pair1(:,4)))&...
                    (dis_s(4)>(Pair1(:,5)./Pair1(:,4))));
    Pair1 = Pair1(Pair1(:,7) == 1,:);
    
    %% Set 2
    Pair2 = Pair;
    
    % Elimination by angle 
    aglmin    = agl2 - ac_er_ang;
    aglmax    = agl2 + ac_er_ang;
    Pair2(:,7) = (Pair2(:,6)>aglmin)&(Pair2(:,6)<aglmax);
    Pair2      =  Pair2(Pair2(:,7)>0,:);
    % Elimination by distance ratio
    dis_s1    = dis3/dis4;
    dis_s2    = dis4/dis3;
    dis_s     =    [dis_s1-ac_er_dis;...
                    dis_s1+ac_er_dis;...
                    dis_s2-ac_er_dis;...
                    dis_s2+ac_er_dis];
    Pair2(:,7) =    ((dis_s(1)<(Pair2(:,4)./Pair2(:,5)))&...
                    (dis_s(2)>(Pair2(:,4)./Pair2(:,5))))|...
                    ((dis_s(3)<(Pair2(:,4)./Pair2(:,5)))&...
                    (dis_s(4)>(Pair2(:,4)./Pair2(:,5))))|...
                    ((dis_s(1)<(Pair2(:,5)./Pair2(:,4)))&...
                    (dis_s(2)>(Pair2(:,5)./Pair2(:,4))))|...
                    ((dis_s(3)<(Pair2(:,5)./Pair2(:,4)))&...
                    (dis_s(4)>(Pair2(:,5)./Pair2(:,4))));
    Pair2 = Pair2(Pair2(:,7) == 1,:);
    Pair2 = Pair2(:,[3 1 2 4 5 6 7]);
    
    % Set 3
    Pair3 = Pair;
    
    % Elimination by angle 
    aglmin    = agl3 - ac_er_ang;
    aglmax    = agl3 + ac_er_ang;
    Pair3(:,7) = (Pair3(:,6)>aglmin)&(Pair3(:,6)<aglmax);
    Pair3      =  Pair3(Pair3(:,7)>0,:);
    % Elimination by distance ratior
    dis_s1    = dis5/dis6;
    dis_s2    = dis6/dis5;
    dis_s     =    [dis_s1-ac_er_dis;...
                    dis_s1+ac_er_dis;...
                    dis_s2-ac_er_dis;...
                    dis_s2+ac_er_dis];
    Pair3(:,7) =    ((dis_s(1)<(Pair3(:,4)./Pair3(:,5)))&...
                    (dis_s(2)>(Pair3(:,4)./Pair3(:,5))))|...
                    ((dis_s(3)<(Pair3(:,4)./Pair3(:,5)))&...
                    (dis_s(4)>(Pair3(:,4)./Pair3(:,5))))|...
                    ((dis_s(1)<(Pair3(:,5)./Pair3(:,4)))&...
                    (dis_s(2)>(Pair3(:,5)./Pair3(:,4))))|...
                    ((dis_s(3)<(Pair3(:,5)./Pair3(:,4)))&...
                    (dis_s(4)>(Pair3(:,5)./Pair3(:,4))));
    Pair3 = Pair3(Pair3(:,7) == 1,:);
    Pair3 = Pair3(:,[2 1 3 4 5 6 7]);
    
    STAR = [Pair1;Pair2;Pair3];
    
    
    
    
    
    
    
    
    
    